
#include <printf.h>
#include "rex_reader.h"

int main() {
    // read the first example generated by rex.cpp:
    const char buffer[] = {
        0x0C, 0x00, 0x00, 0x00, 0x08, 0x00, 0x0C, 0x00,
        0x07, 0x00, 0x08, 0x00, 0x08, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x02, 0x0C, 0x00, 0x00, 0x00,
        0x08, 0x00, 0x0C, 0x00, 0x04, 0x00, 0x08, 0x00,
        0x08, 0x00, 0x00, 0x00, 0x28, 0x00, 0x00, 0x00,
        0x04, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
        0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0A, 0x00,
        0x0C, 0x00, 0x00, 0x00, 0x08, 0x00, 0x06, 0x00,
        0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00,
        0x10, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
        0x02, 0x00, 0x00, 0x00,
    };
    rex_RequestMessage_table_t msg = rex_RequestMessage_as_root(buffer);

    rex_Request_union_type_t reqType = rex_RequestMessage_request_type(msg);
    switch (reqType) {
        case rex_Request_EnterProgramRequest: {
            rex_EnterProgramRequest_table_t req = rex_RequestMessage_request(msg);
            rex_ProgramInstruction_union_vec_t vec = rex_EnterProgramRequest_instructions_union(req);
            size_t len = rex_ProgramInstruction_union_vec_len(vec);
            for (size_t i = 0; i < len; i++) {
                rex_ProgramInstruction_union_t u = rex_ProgramInstruction_union_vec_at(vec, i);
                switch (u.type) {
                    case rex_ProgramInstruction_ReadMemory: {
                        rex_ReadMemory_table_t wr = (rex_ReadMemory_table_t)u.value;
                        printf("read: chip=%s, addr=%06X, size=%04hX",
                            rex_ChipID_name(rex_ReadMemory_chip_id(wr)),
                            rex_ReadMemory_chip_addr(wr),
                            rex_ReadMemory_size(wr)
                        );
                        break;
                    }
                    case rex_ProgramInstruction_WriteMemory: {
                        rex_WriteMemory_table_t wr = (rex_WriteMemory_table_t)u.value;
                        printf("write: chip=%s, addr=%06X, size=%04zX",
                            rex_ChipID_name(rex_WriteMemory_chip_id(wr)),
                            rex_WriteMemory_chip_addr(wr),
                            flatbuffers_uint8_vec_len(rex_WriteMemory_data(wr))
                        );
                        break;
                    }
                }
            }
            break;
        }
        default:
            printf("%s", rex_Request_type_name(reqType));
            break;
    }

    return 0;
}
