#ifndef REX_READER_H
#define REX_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct rex_EnumerateChipsRequest_table *rex_EnumerateChipsRequest_table_t;
typedef struct rex_EnumerateChipsRequest_table *rex_EnumerateChipsRequest_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_EnumerateChipsRequest_vec_t;
typedef flatbuffers_uoffset_t *rex_EnumerateChipsRequest_mutable_vec_t;
typedef const struct rex_Chip_table *rex_Chip_table_t;
typedef struct rex_Chip_table *rex_Chip_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_Chip_vec_t;
typedef flatbuffers_uoffset_t *rex_Chip_mutable_vec_t;
typedef const struct rex_EnumerateChipsResponse_table *rex_EnumerateChipsResponse_table_t;
typedef struct rex_EnumerateChipsResponse_table *rex_EnumerateChipsResponse_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_EnumerateChipsResponse_vec_t;
typedef flatbuffers_uoffset_t *rex_EnumerateChipsResponse_mutable_vec_t;
typedef const struct rex_WriteMemory_table *rex_WriteMemory_table_t;
typedef struct rex_WriteMemory_table *rex_WriteMemory_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_WriteMemory_vec_t;
typedef flatbuffers_uoffset_t *rex_WriteMemory_mutable_vec_t;
typedef const struct rex_ReadMemory_table *rex_ReadMemory_table_t;
typedef struct rex_ReadMemory_table *rex_ReadMemory_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_ReadMemory_vec_t;
typedef flatbuffers_uoffset_t *rex_ReadMemory_mutable_vec_t;
typedef const struct rex_SetTimeout_table *rex_SetTimeout_table_t;
typedef struct rex_SetTimeout_table *rex_SetTimeout_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_SetTimeout_vec_t;
typedef flatbuffers_uoffset_t *rex_SetTimeout_mutable_vec_t;
typedef const struct rex_WaitUntil_table *rex_WaitUntil_table_t;
typedef struct rex_WaitUntil_table *rex_WaitUntil_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_WaitUntil_vec_t;
typedef flatbuffers_uoffset_t *rex_WaitUntil_mutable_vec_t;
typedef const struct rex_WaitWhileZero_table *rex_WaitWhileZero_table_t;
typedef struct rex_WaitWhileZero_table *rex_WaitWhileZero_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_WaitWhileZero_vec_t;
typedef flatbuffers_uoffset_t *rex_WaitWhileZero_mutable_vec_t;
typedef const struct rex_EnterProgramRequest_table *rex_EnterProgramRequest_table_t;
typedef struct rex_EnterProgramRequest_table *rex_EnterProgramRequest_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_EnterProgramRequest_vec_t;
typedef flatbuffers_uoffset_t *rex_EnterProgramRequest_mutable_vec_t;
typedef const struct rex_EnterProgramResponse_table *rex_EnterProgramResponse_table_t;
typedef struct rex_EnterProgramResponse_table *rex_EnterProgramResponse_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_EnterProgramResponse_vec_t;
typedef flatbuffers_uoffset_t *rex_EnterProgramResponse_mutable_vec_t;
typedef const struct rex_ExecuteProgramRequest_table *rex_ExecuteProgramRequest_table_t;
typedef struct rex_ExecuteProgramRequest_table *rex_ExecuteProgramRequest_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_ExecuteProgramRequest_vec_t;
typedef flatbuffers_uoffset_t *rex_ExecuteProgramRequest_mutable_vec_t;
typedef const struct rex_InstructionOutput_table *rex_InstructionOutput_table_t;
typedef struct rex_InstructionOutput_table *rex_InstructionOutput_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_InstructionOutput_vec_t;
typedef flatbuffers_uoffset_t *rex_InstructionOutput_mutable_vec_t;
typedef const struct rex_ExecuteProgramResponse_table *rex_ExecuteProgramResponse_table_t;
typedef struct rex_ExecuteProgramResponse_table *rex_ExecuteProgramResponse_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_ExecuteProgramResponse_vec_t;
typedef flatbuffers_uoffset_t *rex_ExecuteProgramResponse_mutable_vec_t;
typedef const struct rex_RequestMessage_table *rex_RequestMessage_table_t;
typedef struct rex_RequestMessage_table *rex_RequestMessage_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_RequestMessage_vec_t;
typedef flatbuffers_uoffset_t *rex_RequestMessage_mutable_vec_t;
typedef const struct rex_ResponseMessage_table *rex_ResponseMessage_table_t;
typedef struct rex_ResponseMessage_table *rex_ResponseMessage_mutable_table_t;
typedef const flatbuffers_uoffset_t *rex_ResponseMessage_vec_t;
typedef flatbuffers_uoffset_t *rex_ResponseMessage_mutable_vec_t;
#ifndef rex_EnumerateChipsRequest_file_identifier
#define rex_EnumerateChipsRequest_file_identifier 0
#endif
/* deprecated, use rex_EnumerateChipsRequest_file_identifier */
#ifndef rex_EnumerateChipsRequest_identifier
#define rex_EnumerateChipsRequest_identifier 0
#endif
#define rex_EnumerateChipsRequest_type_hash ((flatbuffers_thash_t)0xc12083b4)
#define rex_EnumerateChipsRequest_type_identifier "\xb4\x83\x20\xc1"
#ifndef rex_EnumerateChipsRequest_file_extension
#define rex_EnumerateChipsRequest_file_extension "bin"
#endif
#ifndef rex_Chip_file_identifier
#define rex_Chip_file_identifier 0
#endif
/* deprecated, use rex_Chip_file_identifier */
#ifndef rex_Chip_identifier
#define rex_Chip_identifier 0
#endif
#define rex_Chip_type_hash ((flatbuffers_thash_t)0xabb5b858)
#define rex_Chip_type_identifier "\x58\xb8\xb5\xab"
#ifndef rex_Chip_file_extension
#define rex_Chip_file_extension "bin"
#endif
#ifndef rex_EnumerateChipsResponse_file_identifier
#define rex_EnumerateChipsResponse_file_identifier 0
#endif
/* deprecated, use rex_EnumerateChipsResponse_file_identifier */
#ifndef rex_EnumerateChipsResponse_identifier
#define rex_EnumerateChipsResponse_identifier 0
#endif
#define rex_EnumerateChipsResponse_type_hash ((flatbuffers_thash_t)0xb2d18918)
#define rex_EnumerateChipsResponse_type_identifier "\x18\x89\xd1\xb2"
#ifndef rex_EnumerateChipsResponse_file_extension
#define rex_EnumerateChipsResponse_file_extension "bin"
#endif
#ifndef rex_WriteMemory_file_identifier
#define rex_WriteMemory_file_identifier 0
#endif
/* deprecated, use rex_WriteMemory_file_identifier */
#ifndef rex_WriteMemory_identifier
#define rex_WriteMemory_identifier 0
#endif
#define rex_WriteMemory_type_hash ((flatbuffers_thash_t)0xeeae3b36)
#define rex_WriteMemory_type_identifier "\x36\x3b\xae\xee"
#ifndef rex_WriteMemory_file_extension
#define rex_WriteMemory_file_extension "bin"
#endif
#ifndef rex_ReadMemory_file_identifier
#define rex_ReadMemory_file_identifier 0
#endif
/* deprecated, use rex_ReadMemory_file_identifier */
#ifndef rex_ReadMemory_identifier
#define rex_ReadMemory_identifier 0
#endif
#define rex_ReadMemory_type_hash ((flatbuffers_thash_t)0xd070d535)
#define rex_ReadMemory_type_identifier "\x35\xd5\x70\xd0"
#ifndef rex_ReadMemory_file_extension
#define rex_ReadMemory_file_extension "bin"
#endif
#ifndef rex_SetTimeout_file_identifier
#define rex_SetTimeout_file_identifier 0
#endif
/* deprecated, use rex_SetTimeout_file_identifier */
#ifndef rex_SetTimeout_identifier
#define rex_SetTimeout_identifier 0
#endif
#define rex_SetTimeout_type_hash ((flatbuffers_thash_t)0xd63d61a5)
#define rex_SetTimeout_type_identifier "\xa5\x61\x3d\xd6"
#ifndef rex_SetTimeout_file_extension
#define rex_SetTimeout_file_extension "bin"
#endif
#ifndef rex_WaitUntil_file_identifier
#define rex_WaitUntil_file_identifier 0
#endif
/* deprecated, use rex_WaitUntil_file_identifier */
#ifndef rex_WaitUntil_identifier
#define rex_WaitUntil_identifier 0
#endif
#define rex_WaitUntil_type_hash ((flatbuffers_thash_t)0xaddae9e1)
#define rex_WaitUntil_type_identifier "\xe1\xe9\xda\xad"
#ifndef rex_WaitUntil_file_extension
#define rex_WaitUntil_file_extension "bin"
#endif
#ifndef rex_WaitWhileZero_file_identifier
#define rex_WaitWhileZero_file_identifier 0
#endif
/* deprecated, use rex_WaitWhileZero_file_identifier */
#ifndef rex_WaitWhileZero_identifier
#define rex_WaitWhileZero_identifier 0
#endif
#define rex_WaitWhileZero_type_hash ((flatbuffers_thash_t)0xbd76edca)
#define rex_WaitWhileZero_type_identifier "\xca\xed\x76\xbd"
#ifndef rex_WaitWhileZero_file_extension
#define rex_WaitWhileZero_file_extension "bin"
#endif
#ifndef rex_EnterProgramRequest_file_identifier
#define rex_EnterProgramRequest_file_identifier 0
#endif
/* deprecated, use rex_EnterProgramRequest_file_identifier */
#ifndef rex_EnterProgramRequest_identifier
#define rex_EnterProgramRequest_identifier 0
#endif
#define rex_EnterProgramRequest_type_hash ((flatbuffers_thash_t)0x315470a1)
#define rex_EnterProgramRequest_type_identifier "\xa1\x70\x54\x31"
#ifndef rex_EnterProgramRequest_file_extension
#define rex_EnterProgramRequest_file_extension "bin"
#endif
#ifndef rex_EnterProgramResponse_file_identifier
#define rex_EnterProgramResponse_file_identifier 0
#endif
/* deprecated, use rex_EnterProgramResponse_file_identifier */
#ifndef rex_EnterProgramResponse_identifier
#define rex_EnterProgramResponse_identifier 0
#endif
#define rex_EnterProgramResponse_type_hash ((flatbuffers_thash_t)0x3d4bfc9f)
#define rex_EnterProgramResponse_type_identifier "\x9f\xfc\x4b\x3d"
#ifndef rex_EnterProgramResponse_file_extension
#define rex_EnterProgramResponse_file_extension "bin"
#endif
#ifndef rex_ExecuteProgramRequest_file_identifier
#define rex_ExecuteProgramRequest_file_identifier 0
#endif
/* deprecated, use rex_ExecuteProgramRequest_file_identifier */
#ifndef rex_ExecuteProgramRequest_identifier
#define rex_ExecuteProgramRequest_identifier 0
#endif
#define rex_ExecuteProgramRequest_type_hash ((flatbuffers_thash_t)0xd6158a18)
#define rex_ExecuteProgramRequest_type_identifier "\x18\x8a\x15\xd6"
#ifndef rex_ExecuteProgramRequest_file_extension
#define rex_ExecuteProgramRequest_file_extension "bin"
#endif
#ifndef rex_InstructionOutput_file_identifier
#define rex_InstructionOutput_file_identifier 0
#endif
/* deprecated, use rex_InstructionOutput_file_identifier */
#ifndef rex_InstructionOutput_identifier
#define rex_InstructionOutput_identifier 0
#endif
#define rex_InstructionOutput_type_hash ((flatbuffers_thash_t)0x82db047)
#define rex_InstructionOutput_type_identifier "\x47\xb0\x2d\x08"
#ifndef rex_InstructionOutput_file_extension
#define rex_InstructionOutput_file_extension "bin"
#endif
#ifndef rex_ExecuteProgramResponse_file_identifier
#define rex_ExecuteProgramResponse_file_identifier 0
#endif
/* deprecated, use rex_ExecuteProgramResponse_file_identifier */
#ifndef rex_ExecuteProgramResponse_identifier
#define rex_ExecuteProgramResponse_identifier 0
#endif
#define rex_ExecuteProgramResponse_type_hash ((flatbuffers_thash_t)0x185fb074)
#define rex_ExecuteProgramResponse_type_identifier "\x74\xb0\x5f\x18"
#ifndef rex_ExecuteProgramResponse_file_extension
#define rex_ExecuteProgramResponse_file_extension "bin"
#endif
#ifndef rex_RequestMessage_file_identifier
#define rex_RequestMessage_file_identifier 0
#endif
/* deprecated, use rex_RequestMessage_file_identifier */
#ifndef rex_RequestMessage_identifier
#define rex_RequestMessage_identifier 0
#endif
#define rex_RequestMessage_type_hash ((flatbuffers_thash_t)0x5c227e6e)
#define rex_RequestMessage_type_identifier "\x6e\x7e\x22\x5c"
#ifndef rex_RequestMessage_file_extension
#define rex_RequestMessage_file_extension "bin"
#endif
#ifndef rex_ResponseMessage_file_identifier
#define rex_ResponseMessage_file_identifier 0
#endif
/* deprecated, use rex_ResponseMessage_file_identifier */
#ifndef rex_ResponseMessage_identifier
#define rex_ResponseMessage_identifier 0
#endif
#define rex_ResponseMessage_type_hash ((flatbuffers_thash_t)0x9ff7a5d4)
#define rex_ResponseMessage_type_identifier "\xd4\xa5\xf7\x9f"
#ifndef rex_ResponseMessage_file_extension
#define rex_ResponseMessage_file_extension "bin"
#endif

typedef uint16_t rex_ChipID_enum_t;
__flatbuffers_define_integer_type(rex_ChipID, rex_ChipID_enum_t, 16)
#define rex_ChipID_SNES_WRAM ((rex_ChipID_enum_t)UINT16_C(0))
#define rex_ChipID_SNES_VRAM ((rex_ChipID_enum_t)UINT16_C(1))
#define rex_ChipID_SNES_CGRAM ((rex_ChipID_enum_t)UINT16_C(2))
#define rex_ChipID_SNES_OAM ((rex_ChipID_enum_t)UINT16_C(3))
#define rex_ChipID_SNES_APURAM ((rex_ChipID_enum_t)UINT16_C(4))
#define rex_ChipID_SNES_CART_ROM ((rex_ChipID_enum_t)UINT16_C(32))
#define rex_ChipID_SNES_CART_SRAM ((rex_ChipID_enum_t)UINT16_C(33))
#define rex_ChipID_SNES_CART_SA1_IRAM ((rex_ChipID_enum_t)UINT16_C(34))
#define rex_ChipID_SNES_CART_SA1_BWRAM ((rex_ChipID_enum_t)UINT16_C(35))
#define rex_ChipID_SNES_FXPAK_NMI_EXE ((rex_ChipID_enum_t)UINT16_C(64))

static inline const char *rex_ChipID_name(rex_ChipID_enum_t value)
{
    switch (value) {
    case rex_ChipID_SNES_WRAM: return "SNES_WRAM";
    case rex_ChipID_SNES_VRAM: return "SNES_VRAM";
    case rex_ChipID_SNES_CGRAM: return "SNES_CGRAM";
    case rex_ChipID_SNES_OAM: return "SNES_OAM";
    case rex_ChipID_SNES_APURAM: return "SNES_APURAM";
    case rex_ChipID_SNES_CART_ROM: return "SNES_CART_ROM";
    case rex_ChipID_SNES_CART_SRAM: return "SNES_CART_SRAM";
    case rex_ChipID_SNES_CART_SA1_IRAM: return "SNES_CART_SA1_IRAM";
    case rex_ChipID_SNES_CART_SA1_BWRAM: return "SNES_CART_SA1_BWRAM";
    case rex_ChipID_SNES_FXPAK_NMI_EXE: return "SNES_FXPAK_NMI_EXE";
    default: return "";
    }
}

static inline int rex_ChipID_is_known_value(rex_ChipID_enum_t value)
{
    switch (value) {
    case rex_ChipID_SNES_WRAM: return 1;
    case rex_ChipID_SNES_VRAM: return 1;
    case rex_ChipID_SNES_CGRAM: return 1;
    case rex_ChipID_SNES_OAM: return 1;
    case rex_ChipID_SNES_APURAM: return 1;
    case rex_ChipID_SNES_CART_ROM: return 1;
    case rex_ChipID_SNES_CART_SRAM: return 1;
    case rex_ChipID_SNES_CART_SA1_IRAM: return 1;
    case rex_ChipID_SNES_CART_SA1_BWRAM: return 1;
    case rex_ChipID_SNES_FXPAK_NMI_EXE: return 1;
    default: return 0;
    }
}

typedef uint8_t rex_Comparison_enum_t;
__flatbuffers_define_integer_type(rex_Comparison, rex_Comparison_enum_t, 8)
#define rex_Comparison_Equal ((rex_Comparison_enum_t)UINT8_C(0))
#define rex_Comparison_NotEqual ((rex_Comparison_enum_t)UINT8_C(1))
#define rex_Comparison_LessThan ((rex_Comparison_enum_t)UINT8_C(2))
#define rex_Comparison_LessThanOrEqual ((rex_Comparison_enum_t)UINT8_C(3))
#define rex_Comparison_GreaterThan ((rex_Comparison_enum_t)UINT8_C(4))
#define rex_Comparison_GreaterThanOrEqual ((rex_Comparison_enum_t)UINT8_C(5))

static inline const char *rex_Comparison_name(rex_Comparison_enum_t value)
{
    switch (value) {
    case rex_Comparison_Equal: return "Equal";
    case rex_Comparison_NotEqual: return "NotEqual";
    case rex_Comparison_LessThan: return "LessThan";
    case rex_Comparison_LessThanOrEqual: return "LessThanOrEqual";
    case rex_Comparison_GreaterThan: return "GreaterThan";
    case rex_Comparison_GreaterThanOrEqual: return "GreaterThanOrEqual";
    default: return "";
    }
}

static inline int rex_Comparison_is_known_value(rex_Comparison_enum_t value)
{
    switch (value) {
    case rex_Comparison_Equal: return 1;
    case rex_Comparison_NotEqual: return 1;
    case rex_Comparison_LessThan: return 1;
    case rex_Comparison_LessThanOrEqual: return 1;
    case rex_Comparison_GreaterThan: return 1;
    case rex_Comparison_GreaterThanOrEqual: return 1;
    default: return 0;
    }
}

typedef uint8_t rex_ErrorCode_enum_t;
__flatbuffers_define_integer_type(rex_ErrorCode, rex_ErrorCode_enum_t, 8)
#define rex_ErrorCode_TimedOut ((rex_ErrorCode_enum_t)UINT8_C(254))
#define rex_ErrorCode_Success ((rex_ErrorCode_enum_t)UINT8_C(0))
#define rex_ErrorCode_UnknownChip ((rex_ErrorCode_enum_t)UINT8_C(1))
#define rex_ErrorCode_ChipNotReadable ((rex_ErrorCode_enum_t)UINT8_C(2))
#define rex_ErrorCode_ChipNotWritable ((rex_ErrorCode_enum_t)UINT8_C(3))
#define rex_ErrorCode_ChipAddressOutOfRange ((rex_ErrorCode_enum_t)UINT8_C(4))
#define rex_ErrorCode_PrgmInvalid ((rex_ErrorCode_enum_t)UINT8_C(5))

static inline const char *rex_ErrorCode_name(rex_ErrorCode_enum_t value)
{
    switch (value) {
    case rex_ErrorCode_TimedOut: return "TimedOut";
    case rex_ErrorCode_Success: return "Success";
    case rex_ErrorCode_UnknownChip: return "UnknownChip";
    case rex_ErrorCode_ChipNotReadable: return "ChipNotReadable";
    case rex_ErrorCode_ChipNotWritable: return "ChipNotWritable";
    case rex_ErrorCode_ChipAddressOutOfRange: return "ChipAddressOutOfRange";
    case rex_ErrorCode_PrgmInvalid: return "PrgmInvalid";
    default: return "";
    }
}

static inline int rex_ErrorCode_is_known_value(rex_ErrorCode_enum_t value)
{
    switch (value) {
    case rex_ErrorCode_TimedOut: return 1;
    case rex_ErrorCode_Success: return 1;
    case rex_ErrorCode_UnknownChip: return 1;
    case rex_ErrorCode_ChipNotReadable: return 1;
    case rex_ErrorCode_ChipNotWritable: return 1;
    case rex_ErrorCode_ChipAddressOutOfRange: return 1;
    case rex_ErrorCode_PrgmInvalid: return 1;
    default: return 0;
    }
}



/** //////////////////////////////// */
struct rex_EnumerateChipsRequest_table { uint8_t unused__; };

static inline size_t rex_EnumerateChipsRequest_vec_len(rex_EnumerateChipsRequest_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_EnumerateChipsRequest_table_t rex_EnumerateChipsRequest_vec_at(rex_EnumerateChipsRequest_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_EnumerateChipsRequest_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_EnumerateChipsRequest)


struct rex_Chip_table { uint8_t unused__; };

static inline size_t rex_Chip_vec_len(rex_Chip_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_Chip_table_t rex_Chip_vec_at(rex_Chip_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_Chip_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_Chip)

__flatbuffers_define_scalar_field(0, rex_Chip, chip_id, rex_ChipID, rex_ChipID_enum_t, UINT16_C(0))
__flatbuffers_define_scalar_field(1, rex_Chip, size, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, rex_Chip, flags, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_string_field(3, rex_Chip, name, 0)

struct rex_EnumerateChipsResponse_table { uint8_t unused__; };

static inline size_t rex_EnumerateChipsResponse_vec_len(rex_EnumerateChipsResponse_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_EnumerateChipsResponse_table_t rex_EnumerateChipsResponse_vec_at(rex_EnumerateChipsResponse_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_EnumerateChipsResponse_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_EnumerateChipsResponse)

__flatbuffers_define_vector_field(0, rex_EnumerateChipsResponse, chips, rex_Chip_vec_t, 0)

/** //////////////////////////////// */
struct rex_WriteMemory_table { uint8_t unused__; };

static inline size_t rex_WriteMemory_vec_len(rex_WriteMemory_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_WriteMemory_table_t rex_WriteMemory_vec_at(rex_WriteMemory_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_WriteMemory_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_WriteMemory)

__flatbuffers_define_scalar_field(0, rex_WriteMemory, chip_id, rex_ChipID, rex_ChipID_enum_t, UINT16_C(0))
__flatbuffers_define_scalar_field(1, rex_WriteMemory, chip_addr, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_vector_field(2, rex_WriteMemory, data, flatbuffers_uint8_vec_t, 0)

struct rex_ReadMemory_table { uint8_t unused__; };

static inline size_t rex_ReadMemory_vec_len(rex_ReadMemory_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_ReadMemory_table_t rex_ReadMemory_vec_at(rex_ReadMemory_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_ReadMemory_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_ReadMemory)

__flatbuffers_define_scalar_field(0, rex_ReadMemory, chip_id, rex_ChipID, rex_ChipID_enum_t, UINT16_C(0))
__flatbuffers_define_scalar_field(1, rex_ReadMemory, chip_addr, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, rex_ReadMemory, size, flatbuffers_uint16, uint16_t, UINT16_C(0))

struct rex_SetTimeout_table { uint8_t unused__; };

static inline size_t rex_SetTimeout_vec_len(rex_SetTimeout_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_SetTimeout_table_t rex_SetTimeout_vec_at(rex_SetTimeout_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_SetTimeout_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_SetTimeout)

__flatbuffers_define_scalar_field(0, rex_SetTimeout, clock_cycles, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct rex_WaitUntil_table { uint8_t unused__; };

static inline size_t rex_WaitUntil_vec_len(rex_WaitUntil_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_WaitUntil_table_t rex_WaitUntil_vec_at(rex_WaitUntil_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_WaitUntil_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_WaitUntil)

__flatbuffers_define_scalar_field(0, rex_WaitUntil, chip_id, rex_ChipID, rex_ChipID_enum_t, UINT16_C(0))
__flatbuffers_define_scalar_field(1, rex_WaitUntil, chip_addr, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(2, rex_WaitUntil, cmp_func, rex_Comparison, rex_Comparison_enum_t, UINT8_C(0))
__flatbuffers_define_scalar_field(3, rex_WaitUntil, mask, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(4, rex_WaitUntil, cmp_value, flatbuffers_uint8, uint8_t, UINT8_C(0))

struct rex_WaitWhileZero_table { uint8_t unused__; };

static inline size_t rex_WaitWhileZero_vec_len(rex_WaitWhileZero_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_WaitWhileZero_table_t rex_WaitWhileZero_vec_at(rex_WaitWhileZero_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_WaitWhileZero_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_WaitWhileZero)

__flatbuffers_define_scalar_field(0, rex_WaitWhileZero, chip_id, rex_ChipID, rex_ChipID_enum_t, UINT16_C(0))
__flatbuffers_define_scalar_field(1, rex_WaitWhileZero, chip_addr, flatbuffers_uint32, uint32_t, UINT32_C(0))
typedef uint8_t rex_ProgramInstruction_union_type_t;
__flatbuffers_define_integer_type(rex_ProgramInstruction, rex_ProgramInstruction_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, rex_ProgramInstruction)
#define rex_ProgramInstruction_NONE ((rex_ProgramInstruction_union_type_t)UINT8_C(0))
#define rex_ProgramInstruction_WriteMemory ((rex_ProgramInstruction_union_type_t)UINT8_C(1))
#define rex_ProgramInstruction_ReadMemory ((rex_ProgramInstruction_union_type_t)UINT8_C(2))
#define rex_ProgramInstruction_SetTimeout ((rex_ProgramInstruction_union_type_t)UINT8_C(3))
#define rex_ProgramInstruction_WaitUntil ((rex_ProgramInstruction_union_type_t)UINT8_C(4))
#define rex_ProgramInstruction_WaitWhileZero ((rex_ProgramInstruction_union_type_t)UINT8_C(5))

static inline const char *rex_ProgramInstruction_type_name(rex_ProgramInstruction_union_type_t type)
{
    switch (type) {
    case rex_ProgramInstruction_NONE: return "NONE";
    case rex_ProgramInstruction_WriteMemory: return "WriteMemory";
    case rex_ProgramInstruction_ReadMemory: return "ReadMemory";
    case rex_ProgramInstruction_SetTimeout: return "SetTimeout";
    case rex_ProgramInstruction_WaitUntil: return "WaitUntil";
    case rex_ProgramInstruction_WaitWhileZero: return "WaitWhileZero";
    default: return "";
    }
}

static inline int rex_ProgramInstruction_is_known_type(rex_ProgramInstruction_union_type_t type)
{
    switch (type) {
    case rex_ProgramInstruction_NONE: return 1;
    case rex_ProgramInstruction_WriteMemory: return 1;
    case rex_ProgramInstruction_ReadMemory: return 1;
    case rex_ProgramInstruction_SetTimeout: return 1;
    case rex_ProgramInstruction_WaitUntil: return 1;
    case rex_ProgramInstruction_WaitWhileZero: return 1;
    default: return 0;
    }
}


struct rex_EnterProgramRequest_table { uint8_t unused__; };

static inline size_t rex_EnterProgramRequest_vec_len(rex_EnterProgramRequest_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_EnterProgramRequest_table_t rex_EnterProgramRequest_vec_at(rex_EnterProgramRequest_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_EnterProgramRequest_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_EnterProgramRequest)

__flatbuffers_define_union_vector_field(flatbuffers_, 1, rex_EnterProgramRequest, instructions, rex_ProgramInstruction, 0)

struct rex_EnterProgramResponse_table { uint8_t unused__; };

static inline size_t rex_EnterProgramResponse_vec_len(rex_EnterProgramResponse_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_EnterProgramResponse_table_t rex_EnterProgramResponse_vec_at(rex_EnterProgramResponse_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_EnterProgramResponse_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_EnterProgramResponse)


/** //////////////////////////////// */
struct rex_ExecuteProgramRequest_table { uint8_t unused__; };

static inline size_t rex_ExecuteProgramRequest_vec_len(rex_ExecuteProgramRequest_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_ExecuteProgramRequest_table_t rex_ExecuteProgramRequest_vec_at(rex_ExecuteProgramRequest_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_ExecuteProgramRequest_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_ExecuteProgramRequest)


struct rex_InstructionOutput_table { uint8_t unused__; };

static inline size_t rex_InstructionOutput_vec_len(rex_InstructionOutput_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_InstructionOutput_table_t rex_InstructionOutput_vec_at(rex_InstructionOutput_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_InstructionOutput_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_InstructionOutput)

__flatbuffers_define_scalar_field(0, rex_InstructionOutput, error_code, rex_ErrorCode, rex_ErrorCode_enum_t, UINT8_C(0))
__flatbuffers_define_vector_field(1, rex_InstructionOutput, data, flatbuffers_uint8_vec_t, 0)

struct rex_ExecuteProgramResponse_table { uint8_t unused__; };

static inline size_t rex_ExecuteProgramResponse_vec_len(rex_ExecuteProgramResponse_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_ExecuteProgramResponse_table_t rex_ExecuteProgramResponse_vec_at(rex_ExecuteProgramResponse_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_ExecuteProgramResponse_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_ExecuteProgramResponse)

__flatbuffers_define_vector_field(0, rex_ExecuteProgramResponse, outputs, rex_InstructionOutput_vec_t, 0)
/** //////////////////////////////// */
typedef uint8_t rex_Request_union_type_t;
__flatbuffers_define_integer_type(rex_Request, rex_Request_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, rex_Request)
#define rex_Request_NONE ((rex_Request_union_type_t)UINT8_C(0))
#define rex_Request_EnumerateChipsRequest ((rex_Request_union_type_t)UINT8_C(1))
#define rex_Request_EnterProgramRequest ((rex_Request_union_type_t)UINT8_C(2))
#define rex_Request_ExecuteProgramRequest ((rex_Request_union_type_t)UINT8_C(3))

static inline const char *rex_Request_type_name(rex_Request_union_type_t type)
{
    switch (type) {
    case rex_Request_NONE: return "NONE";
    case rex_Request_EnumerateChipsRequest: return "EnumerateChipsRequest";
    case rex_Request_EnterProgramRequest: return "EnterProgramRequest";
    case rex_Request_ExecuteProgramRequest: return "ExecuteProgramRequest";
    default: return "";
    }
}

static inline int rex_Request_is_known_type(rex_Request_union_type_t type)
{
    switch (type) {
    case rex_Request_NONE: return 1;
    case rex_Request_EnumerateChipsRequest: return 1;
    case rex_Request_EnterProgramRequest: return 1;
    case rex_Request_ExecuteProgramRequest: return 1;
    default: return 0;
    }
}

typedef uint8_t rex_Response_union_type_t;
__flatbuffers_define_integer_type(rex_Response, rex_Response_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, rex_Response)
#define rex_Response_NONE ((rex_Response_union_type_t)UINT8_C(0))
#define rex_Response_EnumerateChipsResponse ((rex_Response_union_type_t)UINT8_C(1))
#define rex_Response_EnterProgramResponse ((rex_Response_union_type_t)UINT8_C(2))
#define rex_Response_ExecuteProgramResponse ((rex_Response_union_type_t)UINT8_C(3))

static inline const char *rex_Response_type_name(rex_Response_union_type_t type)
{
    switch (type) {
    case rex_Response_NONE: return "NONE";
    case rex_Response_EnumerateChipsResponse: return "EnumerateChipsResponse";
    case rex_Response_EnterProgramResponse: return "EnterProgramResponse";
    case rex_Response_ExecuteProgramResponse: return "ExecuteProgramResponse";
    default: return "";
    }
}

static inline int rex_Response_is_known_type(rex_Response_union_type_t type)
{
    switch (type) {
    case rex_Response_NONE: return 1;
    case rex_Response_EnumerateChipsResponse: return 1;
    case rex_Response_EnterProgramResponse: return 1;
    case rex_Response_ExecuteProgramResponse: return 1;
    default: return 0;
    }
}


struct rex_RequestMessage_table { uint8_t unused__; };

static inline size_t rex_RequestMessage_vec_len(rex_RequestMessage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_RequestMessage_table_t rex_RequestMessage_vec_at(rex_RequestMessage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_RequestMessage_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_RequestMessage)

__flatbuffers_define_union_field(flatbuffers_, 1, rex_RequestMessage, request, rex_Request, 0)

struct rex_ResponseMessage_table { uint8_t unused__; };

static inline size_t rex_ResponseMessage_vec_len(rex_ResponseMessage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline rex_ResponseMessage_table_t rex_ResponseMessage_vec_at(rex_ResponseMessage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(rex_ResponseMessage_table_t, vec, i, 0)
__flatbuffers_table_as_root(rex_ResponseMessage)

__flatbuffers_define_union_field(flatbuffers_, 1, rex_ResponseMessage, response, rex_Response, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* REX_READER_H */
